include: package:flutter_lints/flutter.yaml

linter:
  rules:
    # Disable some overly strict rules for package development
    public_member_api_docs: false
    library_private_types_in_public_api: false
    
    # Enable additional rules for better code quality
    prefer_const_constructors: true
    prefer_const_constructors_in_immutables: true
    prefer_const_declarations: true
    prefer_const_literals_to_create_immutables: true
    use_super_parameters: true
    
analyzer:
  exclude:
    - "**/*.g.dart"
    - "**/*.freezed.dart"